### ISSUE TITLE
Consider the drake R package?

### ISSUE THREAD

**Issue by wlandau** [Pakillo/template#7]
From the README:

> Write a makefile or master script to organise and execute all parts of the analysis.

The [`drake` R package](https://github.com/ropensci/drake) is like Make, but for R-focused data science projects. It is not in the reproducibility guide you mentioned, but it is part of rOpenSci.

**Comment by Pakillo** [comment]
Hi @wlandau , thanks for dropping by, and for developing drake!

Yes, I know drake and I'd totally recommend it nowadays. I made this template (following the great pioneer @cboettig) ~3 years ago, when great workflow packages like e.g. remake, drake, workflowr, or rrtools still were not there (or I didn't know about them). Today there are probably much better ways to design and develop projects than this template package, drake being clearly one of the best options. 

Still, people seem to like the simplicity of this (or the idea of projects as packages) so I'll try to make an update soon (e.g. moving to usethis rather than devtools), and keep it alive for the record. But I'll leave this issue open to remind me to update the README pointing out newer approaches like drake.

**Comment by Pakillo** [comment]
Hi @wlandau 
Thanks again for your comment. I've now added several comments (in the README and template makefile) recommending using `drake` or `targets` to manage the project workflow.
Cheers

**Comment by wlandau-lilly** [comment]
Awesome, thanks @Pakillo!
